
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 22.4.1
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.2"

      - name: Clone Repo
        run: |
          git clone https://github.com/MartialBE/one-hub.git
          cd one-hub

      - name: Build Frontend
        env:
          CI: ""
        run: |
          ls
          pwd
          cd web
          yarn install
          VITE_APP_VERSION=$(git describe --tags) yarn run build
          cd ..
      - name: Build binary
        run: |
          go mod download
          
          GOOS=freebsd GOARCH=amd64 go build -ldflags "-s -w -X 'one-api/common/config.Version=$(git describe --tags)' -extldflags '-static'" -o one-api-amd64-freebsd
          cd ..

      # - name: Upload artifact
      #   uses: actions/upload-artifact@main
      #   with:
      #     name: onehub-pre-built
      #     path: |
      #       memos/memos-windows-amd64.tar.gz
      #       memos/memos-freebsd-amd64.tar.gz
      #       memos/memos-darwin-amd64.tar.gz
      #       memos/memos-linux-amd64.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            one-api-amd64-freebsd
          draft: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GT_Token }}
